version: "3.9"

services:
    mysql:
        container_name: mysql
        image: mysql:8.0
        restart: unless-stopped
        env_file: .env
        command: "--default-authentication-plugin=mysql_native_password"

    wordpress:
        container_name: wordpress
        depends_on:
            - mysql
        image: wordpress:php8.0-fpm
        restart: unless-stopped
        environment:
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=${MYSQL_USER?MYSQL_USER not set!}
            - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD?MYSQL_PASSWORD not set!}
            - WORDPRESS_DB_NAME=${MYSQL_DATABASE?MYSQL_DATABASE not set!}
            - WORDPRESS_DEBUG=${WORDPRESS_DEBUG-false}
        volumes:
            - ./wordpress:/var/www/html
        links:
            - "mysql:mysql"

    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./wordpress:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            - PMA_USER=${MYSQL_USER?MYSQL_USER not set!}
            - PMA_PASSWORD=${MYSQL_PASSWORD?MYSQL_PASSWORD not set!}
            - PHP_UPLOAD_MAX_FILESIZE=100MB

    maildev:
        container_name: maildev
        image: djfarrelly/maildev
        restart: unless-stopped
        ports:
            - "3000:80"